#!/bin/bash
#$ -N make_gene_count_table_HMP1-2
#$ -e /u/project/ngarud/daisyche/dbd/logs
#$ -o /u/project/ngarud/daisyche/dbd/logs
#$ -l h_data=8G
#$ -l time=02:00:00
#$ -t 1-194
#$ -m e

. /u/local/Modules/default/init/modules.sh
module load python/2.7

genes_dir=/u/home/d/daisyche/dbd/data/genes

readarray species_genes < $genes_dir/species_genes.txt
species_genes=(null ${species_genes[@]}) # zero to one start index
species=${species_genes[$SGE_TASK_ID]}

python /u/home/d/daisyche/dbd/scripts/make_gene_counts_table.py $species
