#!/bin/bash
#$ -N compress_snps_HMP1-2
#$ -e /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_error
#$ -o /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_output
#$ -l h_data=8G
#$ -l time=02:00:00
#$ -t 1-158
#$ -m e

snps_dir=/u/project/ngarud/Garud_lab/metagenomic_fastq_files/HMP1-2/data/snps

readarray species_snps < $snps_dir/species_snps.txt
species_snps=(null ${species_snps[@]}) # zero to one start index
species=${species_snps[$SGE_TASK_ID]}

echo "Compressing snps for $species"
bzip2 $snps_dir/$species/snps_ref_freq.txt
bzip2 $snps_dir/$species/snps_alt_allele.txt
bzip2 $snps_dir/$species/snps_depth.txt
bzip2 $snps_dir/$species/snps_info.txt
echo "Done :D"
