#!/bin/bash
#$ -N compress_genes_HMP1-2
#$ -e /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_error
#$ -o /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_output
#$ -l h_data=8G
#$ -l time=02:00:00
#$ -t 1-194
#$ -m e

genes_dir=/u/project/ngarud/Garud_lab/metagenomic_fastq_files/HMP1-2/data/genes

readarray species_genes < $genes_dir/species_genes.txt
species_genes=(null ${species_genes[@]}) # zero to one start index
species=${species_genes[$SGE_TASK_ID]}

echo "Compressing genes for $species"
bzip2 $genes_dir/$species/genes_depth.txt
bzip2 $genes_dir/$species/genes_copynum.txt
bzip2 $genes_dir/$species/genes_presabs.txt
bzip2 $genes_dir/$species/genes_reads.txt
echo "Done :D"
