#!/bin/bash
#$ -e /u/home/r/rwolff/oligocolonization/output/get_strainFinder_input_err.txt
#$ -o /u/home/r/rwolff/oligocolonization/output/get_strainFinder_input_out.txt
#$ -cwd
#$ -l h_data=12G
#$ -l time=07:00:00
#$ -m bea
#$ -t 1:186

. /u/local/Modules/default/init/modules.sh
module load anaconda3

python /u/home/r/rwolff/oligocolonization/StrainFinder/scripts/get_strainFinder_input.py $SGE_TASK_ID
