#!/bin/bash
#$ -N FreqDeltas
#$ -e /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_error
#$ -o /u/project/ngarud/daisyche/tmp_intermediate_files/postproc_output
#$ -cwd
#$ -l h_data=8G
#$ -l time=03:00:00
#$ -m bea

. /u/local/Modules/default/init/modules.sh
module load python/2.7

# Run the plot script!
python ~/mother_infant/scripts/snp_freq_changes.py

# python ~/mother_infant/scripts/diversity_vs_snp_changes.py --sweep-type partial

# python ~/mother_infant/scripts/diversity_vs_snp_changes.py --sweep-type full

