#!/bin/bash
#$ -N make_gene_count_table_HMP1-2
#$ -e /u/project/ngarud/daisyche/dbd/logs
#$ -o /u/project/ngarud/daisyche/dbd/logs
#$ -l h_data=8G
#$ -l time=02:00:00
#$ -t 1-194
#$ -m e

genes_dir=/u/project/ngarud/Garud_lab/metagenomic_fastq_files/HMP1-2/data/genes

readarray species_genes < $genes_dir/species_genes.txt
species_genes=(null ${species_genes[@]}) # zero to one start index
species=${species_genes[$SGE_TASK_ID]}

gene_pres_file=$genes_dir/genes_present_$species.txt
touch $gene_pres_file

ncols=$(bzcat $genes_dir/$species/genes_presabs.txt.bz2 | awk -F'\t' '{print NF; exit}')
nrows=$(bzcat $genes_dir/$species/genes_presabs.txt.bz2 | wc -l)
ngenes=$(($nrows - 1))

for i in $(seq 2 $ncols) # Each column is a sample
do		
	sample=$(bzcat $genes_dir/$species/genes_presabs.txt.bz2 | head -1 | cut -f $i)
	count=$(bzcat $genes_dir/$species/genes_presabs.txt.bz2 | cut -f $i | tail -n +2 | paste -sd+ | bc)
	
	echo -n $species >> $gene_pres_file
	echo -ne '\t' >> $gene_pres_file
	echo -n $sample >> $gene_pres_file
	echo -ne '\t' >> $gene_pres_file
	echo -n $ngenes >> $gene_pres_file
	echo -ne '\t' >> $gene_pres_file
	echo $count >> $gene_pres_file
done
