#!/bin/bash
#$ -N Poyet_Core_Genes 
#$ -e /u/project/ngarud/daisyche/dbd/logs/poyet_logs
#$ -o /u/project/ngarud/daisyche/dbd/logs/poyet_logs
#$ -cwd
#$ -l h_data=16G
#$ -l time=20:00:00
#$ -m ea

. /u/local/Modules/default/init/modules.sh
module load python/2.7

python ~/dbd/scripts_poyet/postprocess/calculate_core_genes_all_species.py
